#!/bin/bash
# Comandos útiles para gestionar el contenedor

# Variables
DOCKER_USER="stakazo"
IMAGE_NAME="discografica-ml-system"
CONTAINER_NAME="stakazo-ml-system"

echo "🐳 Comandos Docker disponibles:"
echo ""
echo "1. Ver logs:"
echo "   docker logs -f ${CONTAINER_NAME}"
echo ""
echo "2. Ver stats en tiempo real:"
echo "   docker stats ${CONTAINER_NAME}"
echo ""
echo "3. Entrar al contenedor:"
echo "   docker exec -it ${CONTAINER_NAME} bash"
echo ""
echo "4. Detener:"
echo "   docker stop ${CONTAINER_NAME}"
echo ""
echo "5. Iniciar:"
echo "   docker start ${CONTAINER_NAME}"
echo ""
echo "6. Reiniciar:"
echo "   docker restart ${CONTAINER_NAME}"
echo ""
echo "7. Ver procesos:"
echo "   docker top ${CONTAINER_NAME}"
echo ""
echo "8. Eliminar contenedor:"
echo "   docker rm -f ${CONTAINER_NAME}"
echo ""
echo "9. Pull nueva versión:"
echo "   docker pull ${DOCKER_USER}/${IMAGE_NAME}:latest"
echo ""
echo "10. Push a Docker Hub:"
echo "    docker login -u ${DOCKER_USER}"
echo "    docker push ${DOCKER_USER}/${IMAGE_NAME}:latest"
echo ""
