FROM python:3.11-slim
WORKDIR /app
COPY requirements-workers.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY uploaders/ ./uploaders/
COPY telegram_bot/ ./telegram_bot/
COPY tools/ ./tools/
CMD ["python", "-m", "telegram_bot.bot"]
